# Generated by Django 3.1.7 on 2021-03-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='_type',
            new_name='store_type',
        ),
    ]
