# Generated by Django 3.1.7 on 2021-03-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210307_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Обязательно для создания магазина')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Свойство маркетплейса',
                'verbose_name_plural': 'Свойства маркетплейса',
                'db_table': 'marketplaces_api_properties',
            },
        ),
        migrations.CreateModel(
            name='StoreProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000, verbose_name='Значение')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.marketplaceproperty', verbose_name='Свойство')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Значение свойства магазина',
                'verbose_name_plural': 'Значения свойств магазина',
                'db_table': 'stores_api_properties',
            },
        ),
    ]
