# Generated by Django 3.1.7 on 2021-03-21 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0004_goodsbrand_goodscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.goodscategory', verbose_name='Родительская категория'),
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='Код')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес, кг')),
                ('pack_width', models.FloatField(blank=True, null=True, verbose_name='Ширина упаковки, см')),
                ('pack_length', models.FloatField(blank=True, null=True, verbose_name='Длина упаковки, см')),
                ('pack_height', models.FloatField(blank=True, null=True, verbose_name='Высота упаковки, см')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Штрихкод')),
                ('date_created', models.DateTimeField(blank=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(blank=True, verbose_name='Дата изменения')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.goodsbrand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.goodscategory', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'goods',
                'ordering': ['id'],
                'unique_together': {('sku', 'user')},
            },
        ),
    ]
