# Generated by Django 3.1.7 on 2021-04-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_supplier_warehouse_warehousetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousetype',
            options={'verbose_name': 'Тип склада', 'verbose_name_plural': 'Типы склада'},
        ),
    ]
