# Generated by Django 3.1.7 on 2021-04-22 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0008_auto_20210416_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('token', models.CharField(blank=True, max_length=36, verbose_name='Токен')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Учетная система',
                'verbose_name_plural': 'Учетные системы',
                'db_table': 'systems',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('date_updated', models.DateTimeField(blank=True, verbose_name='Дата изменения')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stores.good', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stores.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Запись об остатке товара',
                'verbose_name_plural': 'Остатки товаров',
                'db_table': 'stock',
                'ordering': ['id'],
            },
        ),
    ]
