# Generated by Django 3.1.7 on 2021-04-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_stock_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(default='123', max_length=200, verbose_name='Символьный код'),
            preserve_default=False,
        ),
    ]
