# Generated by Django 3.1.7 on 2021-05-30 15:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0010_auto_20210425_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок')),
                ('content', models.TextField(blank=True, verbose_name='Условия')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
        ),
    ]
