# Generated by Django 3.1.7 on 2021-05-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_stocksetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocksetting',
            options={'ordering': ['priority'], 'verbose_name': 'Настройка остатков товаров', 'verbose_name_plural': 'Настройки остатков товаров'},
        ),
        migrations.AlterModelTable(
            name='stocksetting',
            table='stock_settings',
        ),
    ]
