# Generated by Django 3.1.7 on 2021-08-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0012_auto_20210530_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('code', models.CharField(max_length=100, verbose_name='Код в маркетплейсе')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_warehouses', related_query_name='warehouse', to='stores.store', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Склад магазина',
                'verbose_name_plural': 'Склады магазинов',
                'db_table': 'store_warehouses',
                'ordering': ['id'],
            },
        ),
    ]
