# Generated by Django 3.1.7 on 2021-08-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_storewarehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksetting',
            name='store',
        ),
        migrations.AddField(
            model_name='stocksetting',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_settings', to='stores.storewarehouse', verbose_name='Склад магазина'),
        ),
    ]
