# Generated by Django 3.1.7 on 2021-09-21 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0014_auto_20210830_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата выполнения')),
                ('success', models.BooleanField(blank=True, default=True, verbose_name='Успех')),
                ('response_status', models.IntegerField(blank=True, default=200, verbose_name='HTTP-код ответа')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Длительность, сек.')),
                ('error', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Описание ошибки')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Запрос')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stores.storewarehouse', verbose_name='Склад магазина')),
            ],
            options={
                'verbose_name': 'Лог обмена',
                'verbose_name_plural': 'Логи обмена',
                'db_table': 'logs',
                'ordering': ['-end_date'],
            },
        ),
    ]
