# Generated by Django 3.1.7 on 2021-09-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_auto_20210926_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stores.marketplace', verbose_name='Маркетплейс'),
        ),
        migrations.AddField(
            model_name='log',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stores.store', verbose_name='Магазин'),
        ),
    ]
