# Generated by Django 3.1.7 on 2021-10-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_auto_20210926_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Переданный остаток')),
                ('success', models.BooleanField(blank=True, default=True, verbose_name='Успешно')),
                ('err_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код ошибки')),
                ('err_msg', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст ошибки')),
                ('good', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stores.good', verbose_name='Товар')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='stores.log', verbose_name='Лог обмена')),
            ],
            options={
                'verbose_name': 'Строка лога обмена',
                'verbose_name_plural': 'Строки логов обмена',
                'db_table': 'log_rows',
                'ordering': ['id'],
            },
        ),
    ]
