# Generated by Django 3.1.7 on 2021-11-04 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_logrow_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrow',
            name='good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stores.good', verbose_name='Товар'),
        ),
    ]
