# Generated by Django 3.1.7 on 2021-11-16 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0021_auto_20211104_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Уникальный код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Общая задача по расписанию',
                'verbose_name_plural': 'Общие задачи по расписанию',
                'db_table': 'jobs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('active', models.BooleanField(blank=True, default=False, verbose_name='Задача активна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to='stores.job', verbose_name='Задача по расписанию')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Пользовательская задача по расписанию',
                'verbose_name_plural': 'Пользовательские задачи по расписанию',
                'db_table': 'user_jobs',
                'ordering': ['id'],
            },
        ),
    ]
