# Generated by Django 3.1.7 on 2021-11-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_job_userjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Уникальный код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Состояние задачи',
                'verbose_name_plural': 'Состояния задач',
                'db_table': 'job_states',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id'], 'verbose_name': 'Задача по расписанию', 'verbose_name_plural': 'Список задач по расписанию'},
        ),
        migrations.AlterModelOptions(
            name='userjob',
            options={'ordering': ['id'], 'verbose_name': 'Периодическая задача пользователя', 'verbose_name_plural': 'Периодические задачи пользователей'},
        ),
        migrations.AddField(
            model_name='userjob',
            name='schedule',
            field=models.CharField(blank=True, max_length=500, verbose_name='Расписание'),
        ),
        migrations.CreateModel(
            name='UserJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Дата завершения')),
                ('success', models.BooleanField(blank=True, default=True, verbose_name='Успешно')),
                ('error', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Ошибка')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='stores.userjob', verbose_name='Задача')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_job_logs', to='stores.jobstate', verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Лог периодической задачи пользователя',
                'verbose_name_plural': 'Логи периодических задач пользователей',
                'db_table': 'user_job_logs',
                'ordering': ['-start_date'],
            },
        ),
    ]
