# Generated by Django 3.1.7 on 2021-11-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_auto_20211116_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Задача активна'),
        ),
    ]
