# Generated by Django 3.1.7 on 2022-03-07 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0026_auto_20211118_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('order_marketplace_id', models.CharField(blank=True, max_length=100, verbose_name='Номер заказа в маркетплейсе')),
                ('order_acc_system_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер заказа в учетной системе')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('items_total', models.FloatField(blank=True, null=True, verbose_name='Сумма товаров')),
                ('subsidy_total', models.FloatField(blank=True, null=True, verbose_name='Сумма компенсации от маркетплейса')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Общая сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ покупателя',
                'verbose_name_plural': 'Заказы покупателей',
                'db_table': 'orders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус заказа покупателя',
                'verbose_name_plural': 'Статусы заказов покупателей',
                'db_table': 'order_statuses',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='marketplace',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Код'),
        ),
        migrations.CreateModel(
            name='OrderMarketplaceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='stores.marketplace', verbose_name='Маркетплейс')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_statuses', to='stores.orderstatus', verbose_name='Системный статус')),
            ],
            options={
                'verbose_name': 'Статус заказа покупателя в маркетплейсе',
                'verbose_name_plural': 'Статусы заказов покупателей в маркетплейсах',
                'db_table': 'order_marketplace_statuses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, verbose_name='Количество')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stores.good', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Строка заказа покупателя',
                'verbose_name_plural': 'Строки заказов покупателей',
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.marketplace', verbose_name='Маркетплейс'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.orderstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.storewarehouse', verbose_name='Склад магазина'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
    ]
